In [1]:
import numpy as np

In [17]:
# Question 1

def vander(arr, N=None, increasing=False):
    if not N:
        N=len(arr)
    result = np.zeros((len(x),N))
    if increasing:
        power = 0
        for col in range(result.shape[1]):
            for row in range(result.shape[0]):
                result[row,col] = arr[row]**power
            power+=1
    else:
        power = N-1
        for col in range(result.shape[1]):
            for row in range(result.shape[0]):
                result[row,col] = arr[row]**power
            power-=1
                
    return result



In [18]:
x = np.array([1, 2, 3, 5])
vander(x, 3)

array([[ 1.,  1.,  1.],
       [ 4.,  2.,  1.],
       [ 9.,  3.,  1.],
       [25.,  5.,  1.]])

In [19]:
x = np.array([1, 2, 3, 5])
vander(x)

array([[  1.,   1.,   1.,   1.],
       [  8.,   4.,   2.,   1.],
       [ 27.,   9.,   3.,   1.],
       [125.,  25.,   5.,   1.]])

In [20]:
x = np.array([1, 2, 3, 5])
vander(x, increasing=True)

array([[  1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.],
       [  1.,   3.,   9.,  27.],
       [  1.,   5.,  25., 125.]])

In [32]:
# Question 2

def moving_avg(x, k):
    n = len(x)
    result = np.zeros(n- k +1)
    for i in range(len(result)):
        result[i] = np.sum(x[:k])/k
        x = np.roll(x,-1)
    return result


In [34]:
test = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
moving_avg(test, 3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])